### ISSUE TITLE
Set up basic Express application

### ISSUE THREAD

**Issue by isithabib** [SchoolOfCode/bc17-w4d2-project-hcd#1]
```[tasklist]
### Tasks
- [x] Update README file with instructions to install express
- [x] Be able to receive a get request
- [x] Send a response saying "Hello World!"
- [x] Show log request in terminal (console.log)
```
