### ISSUE TITLE
Add basic security standards using Helmet

### ISSUE THREAD

**Issue by isithabib** [SchoolOfCode/bc17-w4d2-project-hcd#2]
```[tasklist]
### Tasks
- [x] Read about Helmet package
- [x] Install Helmet in our App
- [x] Import Helmet into Index.js
- [x] Remove header with Helmet
```
