### ISSUE TITLE
Implement functionality to GET all activities for a particular user

### ISSUE THREAD

**Issue by isithabib** [SchoolOfCode/bc17-w4d2-project-hcd#3]
```[tasklist]
### Tasks
- [x] create an activity array
- [x] receive a get request http://localhost:3000/activities
- [x] respond with a list of acitivities (including user_id)
- [x] add it into an async function with a try/catch errors
- [x] add the status code in the response
```
