### ISSUE TITLE
Implement functionality to POST a new activity

### ISSUE THREAD

**Issue by isithabib** [SchoolOfCode/bc17-w4d2-project-hcd#4]
```[tasklist]
### Tasks
- [x] Create a receive POST request containing Activity type and duration
- [x] Assign time stamp and UUID
- [x] Export activity to internal Json file
- [x] Create error message and an incorrect status identifier if unfilled
```
