### ISSUE TITLE
Implement functionality to DELETE an activity

### ISSUE THREAD

**Issue by isithabib** [SchoolOfCode/bc17-w4d2-project-hcd#6]
```[tasklist]
### Tasks
- [ ] Create a delete request
- [ ] Allow request to accept ID
- [ ] Have request delete the matching ID
- [ ] Display correct status code
- [ ] If unable to match IDs show error
```
